
# The design goals for `zstring_view`

## Terminology

### Contract

In this paper, whenever the word 'contract' is used, we _do not_ refer to the C++26 feature known as "contract assertions", but instead refer to the methods of Library API specifications.

### C-string contract

The term _C-string contract_ refers to the convention that the C programming language uses for representing strings:

1. The type is `const char*`
2. The pointer is not null.
3. The pointer points to a valid array of characters.
4. The iteration over the array is guaranteed to reach the zero character without hitting any undefined behavior. The position of this zero character determines the string size.
5. A zero-size string is a valid string value.

Note that under this contract it is impossible for the string to have a zero character within its contents, as -- per the contract -- the first ocurrence of this character indicates the one-past-last character.


## The motivation

A proposal should set out with a very clear goal statement, so that LEWG can evaluate:

* if the goal is worth pursuing;
* if the proposed solution addresses the stated goal.

"A lot of people ask for it" or "there is a lot of similar GitHub libraries"
or " `std` does not yet have a type wth this cobination of properties"
is not a sufficient motivation. As an illustration,
a lot of people ask that C\++ provides a `finally` keyword. The correct response in that case has been to educate the people on C++'s destructors rather than just fulfilling the request.

The motivation that we have identified in https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2026/p3655r4.html[P3655r4] is the experience where:

1. The author of the function will be calling a system function, such as POSIX
   https://www.man7.org/linux/man-pages/man2/openat.2.html[`open`].
2. The author wants to use `std::string_view` as the function parameter type rather than `const char*`.

Such setup "compiles" and could work, but the callers would need to be communicated
and then dyscyplined to only create `string_view` ojects that happen to be zero-terminated.
We are talking about a _precondition_. Other options that the author has is to either use `const char*` as the function parameter type along with the C-string contract, or introduce a new type. In all three cases,
the fact that a pointer to a zero-terminated character array will be used in the implementation is exposed in the function's contract.

So, given that the C-string contract will be used anyway, why not just use `const char *` as the function parameter type, rather than insisting on a new type? The answers could be:

1. To reflect in the type the C-string contract: pointer must not be null,
   the array shall contain the zero character.
2. To enable the type, if so configured, to runtime-enforce the C-string contract.
3. To enable useful, harmless and cheap conversions, like from `std::string`.
4. To avoid the misleading semantics of `operator==` for `const char*` with the C-string contract.

We do not understand the argument in https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2026/p3655r4.html[P3655r4] which says, "to avoid the potential `strlen` overhead".
Ultimately, the `const char*` will be passed to the system function https://www.man7.org/linux/man-pages/man2/openat.2.html[`open`] which will not care whether we know the string size or not:
it will unconditionally iterate over the array until the zero terminator anyway. We cannot change that.

The reminder of the document assumes that the goal of the new type is to be a "C-string contract enforcer".


## Design decisions


### Constructors

The C-string contract enforcement would require three checks.

1. Checking if the pointer is non-null is trivial.
2. Checking if the pointer points to a valid character array is impossible.
3. Checking for a zero character is tricky:
we could iterate over the elements to look for it, but if it isn't there we will reach UB.

The whole motivation for the type is to be able to test #3.
This is doable if in the constructors we are additionally
provided the limit for the iteration.
It is easy to do for some constructors:

1. `zstring_view(string const& s)` -- `s` already guarantees the null terminator.
2. `zstring_view(const char(&a)[N])` -- `N` (a template parameter) is the limit,
and we can check for zero at `N - 1`.

3. Copy/move constructor -- it is safe to assume that we already performed the check when creating the original.

But we definately cannot accept `zstring_view(const char*)` -- we will not be able to verify the contract.
This means that the simplest and intuitive use cases will not work:

```c++
catch(std::exception const& exc)
{
  string s = exc.what();        // ok
  string_view sv = exc.what();  // ok
  zstring_view zv = exc.what(); // compiler error!
}
```

If we allow a constructor from `const char*` we have failed to achieve
the type's goal.

If we only provide constructor `zstring_view(const char*, size_t)`, we either make the usage of this type impossible, or bug prone:

```c++
catch(std::exception const& exc)
{
  size_t Max = 128;  // arbitrary size limit
  zstring_view zv(exc.what(), Max); // compiles, but may be UB
}
```

How do the current implementations address this issue? We are not aware of
many implementations of this tool. We also note the whoever decides to
implement "something like `zstring_view` " is not obliged to state and follow any design goals.
The Standard Library components, on the other hand, should be founded on principles.

Let's take a look at one interesting use case.
https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2026/p3655r4.html[P3655r4]
quotes a revision of https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2025/p3081r1.pdf[P3081]:


> This [`zstring_view`] is one of the commonly-requested features from the
> https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#gslview-views[[GSL]]
> library that does not yet have a std:: equivalent. It was specifically requested by several reviewers of this work.

But if we look at the Microsoft's implementation of the
https://github.com/microsoft/GSL/blob/main/include/gsl/zstring[GSL] library, `zstring` is just an alias on `char*`. Apparently, GSL does not aim at runtime-checking the violations of the C-string contract.

The goal "C-string contract enforcement" seems unimplementable.

We could compromise the goal a bit, and say that the new type either allows
a runtime-verifiable correct construction _or_ provides a very explicit syntax
for uncheckable initialization that is easy to audit:

```c++
catch (std::exception const& exc)
{
  auto zv = zstring_view::RISKY_convert(exc.what()); // ok
}
```

It would still be far from being a drop-in replacement for `const char*` in function parameters.



### The richness of the interface


If the goal is to have a C-string interface with the ability to runtime-enforce it,
then the excessive richness of the `std::string` interface
(such as function `find_last_not_of`) is not necessary.

This rich interface was not necessary in `std::string` in the first place.
It made sense to reprise it in `std::string_view` as the latter's contract is
"treat me as `string` except that I represent a section in the bigger character sequence":

```
                        begin       begin + size
string_view:            ↓           ↓
original sequence: |0|1|2|3|4|5|6|7|8|9|0|

```

But the contract of `zstring_view` (if it were to satisfy the indicated goal) is different.
It is "I am a `const char*` that additionally verifies the C-string contract". Even `operator[]`
is unnecessary: just call `.data()` and iterate over this array.

In an unlikely case where the full interface of `string_view` is required,
`zstring_view` can be cheaply converted to `string_view`.


=== String’s length

`string` stores its length explicitly, so that it can treat the zero-character
as an ordinary character. `string_view` sores its length because this is necessary to
represent a subsection of a longer character sequence.

In contrast, the contract of `zstring_view` is that it will ultimately
be passed to a function like POSIX
https://www.man7.org/linux/man-pages/man2/openat.2.html[`open`] and its size will
be determined by iterating throughout the sequence until the zero-character.
The iteration will be performed, no matter what we do!
Keeping this number doesn't add value here, but on the other hand would pose a new problem:
this explicit size and the result of `strlen` would have to be kept in sync,
and this is difficult when zero characters are present in the sequence before the end of explicit length.

```c++
string s("A\0B", 3);
string_view sv("A\0B", 3);
zstring_view zs("A\0B", 3);

assert (s.length() != strlen(s.data()));   // ok: `strlen(s.data())` is not the length
assert (sv.length() != strlen(sv.data())); // ok: `strlen(sv.data())` is not the length
assert (zs.length() != strlen(zs.data())); // disaster: `strlen(zs.data())` is the length
```

Assuming the goal of `zstring_view` is "a `const char*` that additionally
verifies the C-string contract", consistent solutions would be:

 1. Do not provide member `length()` or `size()`.
 2. Make these members equivalent to `strlen(data())`.
 3. Add a precondition, potentially runtime-enforced,
    that zero-characters in the middle are not allowed.

It may still make sense to have the `size_t` member but with a different interpretation.
If `zstring_view` provides `operator[]`, this member could be used as help to runtime-enforce
the precondition that the index is "in the right range".

Option #2 still requires other questions to be answered: shall this value of length be computed upon construction?
If so, this a waste in the very basic use case:

```c++
zstring_view zs("may contain a \0 char"); // 1st range iteration
fopen(zs.data());                         // 2nd range iteration
```

We could compute the length when it is first needed and then cache the result.
But this causes data-race issues.


## Recommendations

We recommend the following.

 1. LEWG shall not approve any paper proposing a library component
    that does not clearly state its design goal. This is necessary for everyone in WG21
    to be clear on what the goal is, to be able to assess ig the goal is worth pursuing,
    and if the proposed solution actually addresses the goal.

 2. We observe that
    https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2026/p3655r4.html[P3655r4]
    does not express the goal clearly enough. We described what we _believe_ to
    be the goal: a `const char*` with the C-string contract enforcement.
    Our further analysis is based on this assumed goal.

 3. Based on our assumption, we conclude that the design proposed in
    https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2026/p3655r4.html[P3655r4]
    does not satisfy the goal. In fact, we cannot see any design that would.



## References

 * https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p2176r0.html
 * https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2026/p3655r4.html
 * https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2025/p3697r0.html
