Capy's design is driven by the needs of the network I/O processing, 
where a piece of the program, in order to continue, needs to wait for an I/O operation to finish,
but when this happens is unpredictable. The challenge here is:

 1. To utilize this time of as efficiently as possible, processing other tasks.
 2. To avoid any concurrency or lifetime management bugs.
 3. To have the user code be simple and intuitive.

To achieve this, Capy utilizes the _proactor_ pattern hidden behind the coroutine `co_await` mechanism. I this pattern, 
when the user needs an I/O operation to be performed to see its results, they:

 1. Schedule in the I/O runtime an operation to be performed.
 2. Register a piece of code to be invoked when the I/O operation finishes.

This is exactly what happens when you write:

[source,cpp]
----
process(co_await stream.read_some(buffer));  /*
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~     schedule I/O operation; register the cotorutine resumption when I/O finishes
^~~~~~~                                       to be invoked after I/O finishes     
                                              */
----

While the function body reads as sequential business logic, behind the coroutine mechanism, 
a call is made to to an I/O runtime, and a "task" is registered in its queue. 
