Capy is a C++20, compiled library providing abstractions, vocabulary types and idioms necessary
to write programs with event-driven control flows
-- such as I/O -- in a way that maes them efficient and manageable: structured and hard to get wrong.

Coroutines are used to represent the control flow: the program logic is described in a sequential way,
even though "continutions" are being registered in the execution environment behind the scenes.

I/O operations represented via a concept of a _stream_, which consumes and populates _buffer sequences_.
You also get type-erased wpappers for streams, so that the programs can compile fast, without triggering
many template instantiations.

It offers a number of task synchronization mechanisms, ranging from low-level, like async mutexes and events,
to high-level, like _strands_ and `when_all`/`when_any` "joins".

Libraries that want to provide concrete I/O implementations -- like those based on `epoll` or `io_uring` --
can plug to Capy's system via the `IoAwaitable`-protocol, which describes how the tasks can be scheduled, stopped
and have their memory allocated.

You also get the testing tools that allow you to test your asynchronous flows in a deterministic way.


== What Capy is Not

While capy offers interfaces for dealing with I/O, it does not process I/O itself. For that, you will neet
to use Capy in tandem with a Capy-conformant library. This can be either your home-grown one, or Corosio.

- - - - - - - - - - - - - - - - -

Synchronization tools
